# Generated by Django 4.2.1 on 2023-10-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_user_followers_postmodel_likemodel_commentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
