# Generated by Django 4.2.1 on 2023-10-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likemodel",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="network.postmodel",
            ),
        ),
    ]
