# Generated by Django 4.2.1 on 2023-10-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_user_following_alter_user_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="comments_on_post", to="network.commentmodel"
            ),
        ),
    ]
