# Generated by Django 4.2.1 on 2023-10-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_postmodel_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postmodel",
            name="comments",
        ),
    ]
